FROM golang:1.22-alpine

RUN apk add --no-cache git bash

RUN go install github.com/cosmtrek/air@latest

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

EXPOSE 8765

CMD ["air", "-c", ".air.toml"]
